#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLinqToExpressions
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KuzeyYeli")]
	public partial class KuzeyYeliDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUrunler(Urunler instance);
    partial void UpdateUrunler(Urunler instance);
    partial void DeleteUrunler(Urunler instance);
    partial void InsertBolge(Bolge instance);
    partial void UpdateBolge(Bolge instance);
    partial void DeleteBolge(Bolge instance);
    partial void InsertBolgeler(Bolgeler instance);
    partial void UpdateBolgeler(Bolgeler instance);
    partial void DeleteBolgeler(Bolgeler instance);
    partial void InsertKategoriler(Kategoriler instance);
    partial void UpdateKategoriler(Kategoriler instance);
    partial void DeleteKategoriler(Kategoriler instance);
    partial void InsertMusteriDemographic(MusteriDemographic instance);
    partial void UpdateMusteriDemographic(MusteriDemographic instance);
    partial void DeleteMusteriDemographic(MusteriDemographic instance);
    partial void InsertMusteriler(Musteriler instance);
    partial void UpdateMusteriler(Musteriler instance);
    partial void DeleteMusteriler(Musteriler instance);
    partial void InsertMusteriMusteriDemo(MusteriMusteriDemo instance);
    partial void UpdateMusteriMusteriDemo(MusteriMusteriDemo instance);
    partial void DeleteMusteriMusteriDemo(MusteriMusteriDemo instance);
    partial void InsertNakliyeciler(Nakliyeciler instance);
    partial void UpdateNakliyeciler(Nakliyeciler instance);
    partial void DeleteNakliyeciler(Nakliyeciler instance);
    partial void InsertPersonelBolgeler(PersonelBolgeler instance);
    partial void UpdatePersonelBolgeler(PersonelBolgeler instance);
    partial void DeletePersonelBolgeler(PersonelBolgeler instance);
    partial void InsertPersoneller(Personeller instance);
    partial void UpdatePersoneller(Personeller instance);
    partial void DeletePersoneller(Personeller instance);
    partial void InsertSatisDetay(SatisDetay instance);
    partial void UpdateSatisDetay(SatisDetay instance);
    partial void DeleteSatisDetay(SatisDetay instance);
    partial void InsertSatislar(Satislar instance);
    partial void UpdateSatislar(Satislar instance);
    partial void DeleteSatislar(Satislar instance);
    partial void InsertTedarikciler(Tedarikciler instance);
    partial void UpdateTedarikciler(Tedarikciler instance);
    partial void DeleteTedarikciler(Tedarikciler instance);
    #endregion
		
		public KuzeyYeliDataContext() : 
				base(global::EntityLinqToExpressions.Properties.Settings.Default.KuzeyYeliConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KuzeyYeliDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KuzeyYeliDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KuzeyYeliDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KuzeyYeliDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Urunler> Urunlers
		{
			get
			{
				return this.GetTable<Urunler>();
			}
		}
		
		public System.Data.Linq.Table<Bolge> Bolges
		{
			get
			{
				return this.GetTable<Bolge>();
			}
		}
		
		public System.Data.Linq.Table<Bolgeler> Bolgelers
		{
			get
			{
				return this.GetTable<Bolgeler>();
			}
		}
		
		public System.Data.Linq.Table<Kategoriler> Kategorilers
		{
			get
			{
				return this.GetTable<Kategoriler>();
			}
		}
		
		public System.Data.Linq.Table<MusteriDemographic> MusteriDemographics
		{
			get
			{
				return this.GetTable<MusteriDemographic>();
			}
		}
		
		public System.Data.Linq.Table<Musteriler> Musterilers
		{
			get
			{
				return this.GetTable<Musteriler>();
			}
		}
		
		public System.Data.Linq.Table<MusteriMusteriDemo> MusteriMusteriDemos
		{
			get
			{
				return this.GetTable<MusteriMusteriDemo>();
			}
		}
		
		public System.Data.Linq.Table<Nakliyeciler> Nakliyecilers
		{
			get
			{
				return this.GetTable<Nakliyeciler>();
			}
		}
		
		public System.Data.Linq.Table<PersonelBolgeler> PersonelBolgelers
		{
			get
			{
				return this.GetTable<PersonelBolgeler>();
			}
		}
		
		public System.Data.Linq.Table<Personeller> Personellers
		{
			get
			{
				return this.GetTable<Personeller>();
			}
		}
		
		public System.Data.Linq.Table<SatisDetay> SatisDetays
		{
			get
			{
				return this.GetTable<SatisDetay>();
			}
		}
		
		public System.Data.Linq.Table<Satislar> Satislars
		{
			get
			{
				return this.GetTable<Satislar>();
			}
		}
		
		public System.Data.Linq.Table<Tedarikciler> Tedarikcilers
		{
			get
			{
				return this.GetTable<Tedarikciler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urunler")]
	public partial class Urunler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UrunID;
		
		private string _UrunAdi;
		
		private System.Nullable<int> _TedarikciID;
		
		private System.Nullable<int> _KategoriID;
		
		private string _BirimdekiMiktar;
		
		private System.Nullable<decimal> _Fiyat;
		
		private System.Nullable<short> _Stok;
		
		private System.Nullable<short> _YeniSatis;
		
		private System.Nullable<short> _EnAzYenidenSatisMikatari;
		
		private bool _Sonlandi;
		
		private EntitySet<SatisDetay> _SatisDetays;
		
		private EntityRef<Kategoriler> _Kategoriler;
		
		private EntityRef<Tedarikciler> _Tedarikciler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrunIDChanging(int value);
    partial void OnUrunIDChanged();
    partial void OnUrunAdiChanging(string value);
    partial void OnUrunAdiChanged();
    partial void OnTedarikciIDChanging(System.Nullable<int> value);
    partial void OnTedarikciIDChanged();
    partial void OnKategoriIDChanging(System.Nullable<int> value);
    partial void OnKategoriIDChanged();
    partial void OnBirimdekiMiktarChanging(string value);
    partial void OnBirimdekiMiktarChanged();
    partial void OnFiyatChanging(System.Nullable<decimal> value);
    partial void OnFiyatChanged();
    partial void OnStokChanging(System.Nullable<short> value);
    partial void OnStokChanged();
    partial void OnYeniSatisChanging(System.Nullable<short> value);
    partial void OnYeniSatisChanged();
    partial void OnEnAzYenidenSatisMikatariChanging(System.Nullable<short> value);
    partial void OnEnAzYenidenSatisMikatariChanged();
    partial void OnSonlandiChanging(bool value);
    partial void OnSonlandiChanged();
    #endregion
		
		public Urunler()
		{
			this._SatisDetays = new EntitySet<SatisDetay>(new Action<SatisDetay>(this.attach_SatisDetays), new Action<SatisDetay>(this.detach_SatisDetays));
			this._Kategoriler = default(EntityRef<Kategoriler>);
			this._Tedarikciler = default(EntityRef<Tedarikciler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this.OnUrunAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunAdi = value;
					this.SendPropertyChanged("UrunAdi");
					this.OnUrunAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TedarikciID", DbType="Int")]
		public System.Nullable<int> TedarikciID
		{
			get
			{
				return this._TedarikciID;
			}
			set
			{
				if ((this._TedarikciID != value))
				{
					if (this._Tedarikciler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTedarikciIDChanging(value);
					this.SendPropertyChanging();
					this._TedarikciID = value;
					this.SendPropertyChanged("TedarikciID");
					this.OnTedarikciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", DbType="Int")]
		public System.Nullable<int> KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					if (this._Kategoriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirimdekiMiktar", DbType="NVarChar(20)")]
		public string BirimdekiMiktar
		{
			get
			{
				return this._BirimdekiMiktar;
			}
			set
			{
				if ((this._BirimdekiMiktar != value))
				{
					this.OnBirimdekiMiktarChanging(value);
					this.SendPropertyChanging();
					this._BirimdekiMiktar = value;
					this.SendPropertyChanged("BirimdekiMiktar");
					this.OnBirimdekiMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Money")]
		public System.Nullable<decimal> Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stok", DbType="SmallInt")]
		public System.Nullable<short> Stok
		{
			get
			{
				return this._Stok;
			}
			set
			{
				if ((this._Stok != value))
				{
					this.OnStokChanging(value);
					this.SendPropertyChanging();
					this._Stok = value;
					this.SendPropertyChanged("Stok");
					this.OnStokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeniSatis", DbType="SmallInt")]
		public System.Nullable<short> YeniSatis
		{
			get
			{
				return this._YeniSatis;
			}
			set
			{
				if ((this._YeniSatis != value))
				{
					this.OnYeniSatisChanging(value);
					this.SendPropertyChanging();
					this._YeniSatis = value;
					this.SendPropertyChanged("YeniSatis");
					this.OnYeniSatisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnAzYenidenSatisMikatari", DbType="SmallInt")]
		public System.Nullable<short> EnAzYenidenSatisMikatari
		{
			get
			{
				return this._EnAzYenidenSatisMikatari;
			}
			set
			{
				if ((this._EnAzYenidenSatisMikatari != value))
				{
					this.OnEnAzYenidenSatisMikatariChanging(value);
					this.SendPropertyChanging();
					this._EnAzYenidenSatisMikatari = value;
					this.SendPropertyChanged("EnAzYenidenSatisMikatari");
					this.OnEnAzYenidenSatisMikatariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonlandi", DbType="Bit NOT NULL")]
		public bool Sonlandi
		{
			get
			{
				return this._Sonlandi;
			}
			set
			{
				if ((this._Sonlandi != value))
				{
					this.OnSonlandiChanging(value);
					this.SendPropertyChanging();
					this._Sonlandi = value;
					this.SendPropertyChanged("Sonlandi");
					this.OnSonlandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urunler_SatisDetay", Storage="_SatisDetays", ThisKey="UrunID", OtherKey="UrunID")]
		public EntitySet<SatisDetay> SatisDetays
		{
			get
			{
				return this._SatisDetays;
			}
			set
			{
				this._SatisDetays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoriler_Urunler", Storage="_Kategoriler", ThisKey="KategoriID", OtherKey="KategoriID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Kategoriler Kategoriler
		{
			get
			{
				return this._Kategoriler.Entity;
			}
			set
			{
				Kategoriler previousValue = this._Kategoriler.Entity;
				if (((previousValue != value) 
							|| (this._Kategoriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategoriler.Entity = null;
						previousValue.Urunlers.Remove(this);
					}
					this._Kategoriler.Entity = value;
					if ((value != null))
					{
						value.Urunlers.Add(this);
						this._KategoriID = value.KategoriID;
					}
					else
					{
						this._KategoriID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategoriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tedarikciler_Urunler", Storage="_Tedarikciler", ThisKey="TedarikciID", OtherKey="TedarikciID", IsForeignKey=true, DeleteRule="CASCADE")]
		public Tedarikciler Tedarikciler
		{
			get
			{
				return this._Tedarikciler.Entity;
			}
			set
			{
				Tedarikciler previousValue = this._Tedarikciler.Entity;
				if (((previousValue != value) 
							|| (this._Tedarikciler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tedarikciler.Entity = null;
						previousValue.Urunlers.Remove(this);
					}
					this._Tedarikciler.Entity = value;
					if ((value != null))
					{
						value.Urunlers.Add(this);
						this._TedarikciID = value.TedarikciID;
					}
					else
					{
						this._TedarikciID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tedarikciler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SatisDetays(SatisDetay entity)
		{
			this.SendPropertyChanging();
			entity.Urunler = this;
		}
		
		private void detach_SatisDetays(SatisDetay entity)
		{
			this.SendPropertyChanging();
			entity.Urunler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bolge")]
	public partial class Bolge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BolgeID;
		
		private string _BolgeTanimi;
		
		private EntitySet<Bolgeler> _Bolgelers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBolgeIDChanging(int value);
    partial void OnBolgeIDChanged();
    partial void OnBolgeTanimiChanging(string value);
    partial void OnBolgeTanimiChanged();
    #endregion
		
		public Bolge()
		{
			this._Bolgelers = new EntitySet<Bolgeler>(new Action<Bolgeler>(this.attach_Bolgelers), new Action<Bolgeler>(this.detach_Bolgelers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolgeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BolgeID
		{
			get
			{
				return this._BolgeID;
			}
			set
			{
				if ((this._BolgeID != value))
				{
					this.OnBolgeIDChanging(value);
					this.SendPropertyChanging();
					this._BolgeID = value;
					this.SendPropertyChanged("BolgeID");
					this.OnBolgeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolgeTanimi", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string BolgeTanimi
		{
			get
			{
				return this._BolgeTanimi;
			}
			set
			{
				if ((this._BolgeTanimi != value))
				{
					this.OnBolgeTanimiChanging(value);
					this.SendPropertyChanging();
					this._BolgeTanimi = value;
					this.SendPropertyChanged("BolgeTanimi");
					this.OnBolgeTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolge_Bolgeler", Storage="_Bolgelers", ThisKey="BolgeID", OtherKey="BolgeID")]
		public EntitySet<Bolgeler> Bolgelers
		{
			get
			{
				return this._Bolgelers;
			}
			set
			{
				this._Bolgelers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bolgelers(Bolgeler entity)
		{
			this.SendPropertyChanging();
			entity.Bolge = this;
		}
		
		private void detach_Bolgelers(Bolgeler entity)
		{
			this.SendPropertyChanging();
			entity.Bolge = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bolgeler")]
	public partial class Bolgeler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TerritoryID;
		
		private string _TerritoryTanimi;
		
		private int _BolgeID;
		
		private EntitySet<PersonelBolgeler> _PersonelBolgelers;
		
		private EntityRef<Bolge> _Bolge;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTerritoryIDChanging(string value);
    partial void OnTerritoryIDChanged();
    partial void OnTerritoryTanimiChanging(string value);
    partial void OnTerritoryTanimiChanged();
    partial void OnBolgeIDChanging(int value);
    partial void OnBolgeIDChanged();
    #endregion
		
		public Bolgeler()
		{
			this._PersonelBolgelers = new EntitySet<PersonelBolgeler>(new Action<PersonelBolgeler>(this.attach_PersonelBolgelers), new Action<PersonelBolgeler>(this.detach_PersonelBolgelers));
			this._Bolge = default(EntityRef<Bolge>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TerritoryID
		{
			get
			{
				return this._TerritoryID;
			}
			set
			{
				if ((this._TerritoryID != value))
				{
					this.OnTerritoryIDChanging(value);
					this.SendPropertyChanging();
					this._TerritoryID = value;
					this.SendPropertyChanged("TerritoryID");
					this.OnTerritoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryTanimi", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TerritoryTanimi
		{
			get
			{
				return this._TerritoryTanimi;
			}
			set
			{
				if ((this._TerritoryTanimi != value))
				{
					this.OnTerritoryTanimiChanging(value);
					this.SendPropertyChanging();
					this._TerritoryTanimi = value;
					this.SendPropertyChanged("TerritoryTanimi");
					this.OnTerritoryTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolgeID", DbType="Int NOT NULL")]
		public int BolgeID
		{
			get
			{
				return this._BolgeID;
			}
			set
			{
				if ((this._BolgeID != value))
				{
					if (this._Bolge.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBolgeIDChanging(value);
					this.SendPropertyChanging();
					this._BolgeID = value;
					this.SendPropertyChanged("BolgeID");
					this.OnBolgeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolgeler_PersonelBolgeler", Storage="_PersonelBolgelers", ThisKey="TerritoryID", OtherKey="TerritoryID")]
		public EntitySet<PersonelBolgeler> PersonelBolgelers
		{
			get
			{
				return this._PersonelBolgelers;
			}
			set
			{
				this._PersonelBolgelers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolge_Bolgeler", Storage="_Bolge", ThisKey="BolgeID", OtherKey="BolgeID", IsForeignKey=true)]
		public Bolge Bolge
		{
			get
			{
				return this._Bolge.Entity;
			}
			set
			{
				Bolge previousValue = this._Bolge.Entity;
				if (((previousValue != value) 
							|| (this._Bolge.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bolge.Entity = null;
						previousValue.Bolgelers.Remove(this);
					}
					this._Bolge.Entity = value;
					if ((value != null))
					{
						value.Bolgelers.Add(this);
						this._BolgeID = value.BolgeID;
					}
					else
					{
						this._BolgeID = default(int);
					}
					this.SendPropertyChanged("Bolge");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PersonelBolgelers(PersonelBolgeler entity)
		{
			this.SendPropertyChanging();
			entity.Bolgeler = this;
		}
		
		private void detach_PersonelBolgelers(PersonelBolgeler entity)
		{
			this.SendPropertyChanging();
			entity.Bolgeler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategoriler")]
	public partial class Kategoriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KategoriID;
		
		private string _KategoriAdi;
		
		private string _Tanimi;
		
		private System.Data.Linq.Binary _Resim;
		
		private EntitySet<Urunler> _Urunlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKategoriIDChanging(int value);
    partial void OnKategoriIDChanged();
    partial void OnKategoriAdiChanging(string value);
    partial void OnKategoriAdiChanged();
    partial void OnTanimiChanging(string value);
    partial void OnTanimiChanged();
    partial void OnResimChanging(System.Data.Linq.Binary value);
    partial void OnResimChanged();
    #endregion
		
		public Kategoriler()
		{
			this._Urunlers = new EntitySet<Urunler>(new Action<Urunler>(this.attach_Urunlers), new Action<Urunler>(this.detach_Urunlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KategoriID
		{
			get
			{
				return this._KategoriID;
			}
			set
			{
				if ((this._KategoriID != value))
				{
					this.OnKategoriIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriID = value;
					this.SendPropertyChanged("KategoriID");
					this.OnKategoriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriAdi", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string KategoriAdi
		{
			get
			{
				return this._KategoriAdi;
			}
			set
			{
				if ((this._KategoriAdi != value))
				{
					this.OnKategoriAdiChanging(value);
					this.SendPropertyChanging();
					this._KategoriAdi = value;
					this.SendPropertyChanged("KategoriAdi");
					this.OnKategoriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tanimi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Tanimi
		{
			get
			{
				return this._Tanimi;
			}
			set
			{
				if ((this._Tanimi != value))
				{
					this.OnTanimiChanging(value);
					this.SendPropertyChanging();
					this._Tanimi = value;
					this.SendPropertyChanged("Tanimi");
					this.OnTanimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoriler_Urunler", Storage="_Urunlers", ThisKey="KategoriID", OtherKey="KategoriID")]
		public EntitySet<Urunler> Urunlers
		{
			get
			{
				return this._Urunlers;
			}
			set
			{
				this._Urunlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Kategoriler = this;
		}
		
		private void detach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Kategoriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MusteriDemographics")]
	public partial class MusteriDemographic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MusteriTypeID;
		
		private string _MusteriDesc;
		
		private EntitySet<MusteriMusteriDemo> _MusteriMusteriDemos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriTypeIDChanging(string value);
    partial void OnMusteriTypeIDChanged();
    partial void OnMusteriDescChanging(string value);
    partial void OnMusteriDescChanged();
    #endregion
		
		public MusteriDemographic()
		{
			this._MusteriMusteriDemos = new EntitySet<MusteriMusteriDemo>(new Action<MusteriMusteriDemo>(this.attach_MusteriMusteriDemos), new Action<MusteriMusteriDemo>(this.detach_MusteriMusteriDemos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriTypeID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MusteriTypeID
		{
			get
			{
				return this._MusteriTypeID;
			}
			set
			{
				if ((this._MusteriTypeID != value))
				{
					this.OnMusteriTypeIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriTypeID = value;
					this.SendPropertyChanged("MusteriTypeID");
					this.OnMusteriTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriDesc", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MusteriDesc
		{
			get
			{
				return this._MusteriDesc;
			}
			set
			{
				if ((this._MusteriDesc != value))
				{
					this.OnMusteriDescChanging(value);
					this.SendPropertyChanging();
					this._MusteriDesc = value;
					this.SendPropertyChanged("MusteriDesc");
					this.OnMusteriDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MusteriDemographic_MusteriMusteriDemo", Storage="_MusteriMusteriDemos", ThisKey="MusteriTypeID", OtherKey="MusteriTypeID")]
		public EntitySet<MusteriMusteriDemo> MusteriMusteriDemos
		{
			get
			{
				return this._MusteriMusteriDemos;
			}
			set
			{
				this._MusteriMusteriDemos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MusteriMusteriDemos(MusteriMusteriDemo entity)
		{
			this.SendPropertyChanging();
			entity.MusteriDemographic = this;
		}
		
		private void detach_MusteriMusteriDemos(MusteriMusteriDemo entity)
		{
			this.SendPropertyChanging();
			entity.MusteriDemographic = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteriler")]
	public partial class Musteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MusteriID;
		
		private string _SirketAdi;
		
		private string _MusteriAdi;
		
		private string _MusteriUnvani;
		
		private string _Adres;
		
		private string _Sehir;
		
		private string _Bolge;
		
		private string _PostaKodu;
		
		private string _Ulke;
		
		private string _Telefon;
		
		private string _Faks;
		
		private EntitySet<MusteriMusteriDemo> _MusteriMusteriDemos;
		
		private EntitySet<Satislar> _Satislars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriIDChanging(string value);
    partial void OnMusteriIDChanged();
    partial void OnSirketAdiChanging(string value);
    partial void OnSirketAdiChanged();
    partial void OnMusteriAdiChanging(string value);
    partial void OnMusteriAdiChanged();
    partial void OnMusteriUnvaniChanging(string value);
    partial void OnMusteriUnvaniChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnBolgeChanging(string value);
    partial void OnBolgeChanged();
    partial void OnPostaKoduChanging(string value);
    partial void OnPostaKoduChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnFaksChanging(string value);
    partial void OnFaksChanged();
    #endregion
		
		public Musteriler()
		{
			this._MusteriMusteriDemos = new EntitySet<MusteriMusteriDemo>(new Action<MusteriMusteriDemo>(this.attach_MusteriMusteriDemos), new Action<MusteriMusteriDemo>(this.detach_MusteriMusteriDemos));
			this._Satislars = new EntitySet<Satislar>(new Action<Satislar>(this.attach_Satislars), new Action<Satislar>(this.detach_Satislars));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SirketAdi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string SirketAdi
		{
			get
			{
				return this._SirketAdi;
			}
			set
			{
				if ((this._SirketAdi != value))
				{
					this.OnSirketAdiChanging(value);
					this.SendPropertyChanging();
					this._SirketAdi = value;
					this.SendPropertyChanged("SirketAdi");
					this.OnSirketAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAdi", DbType="NVarChar(30)")]
		public string MusteriAdi
		{
			get
			{
				return this._MusteriAdi;
			}
			set
			{
				if ((this._MusteriAdi != value))
				{
					this.OnMusteriAdiChanging(value);
					this.SendPropertyChanging();
					this._MusteriAdi = value;
					this.SendPropertyChanged("MusteriAdi");
					this.OnMusteriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriUnvani", DbType="NVarChar(30)")]
		public string MusteriUnvani
		{
			get
			{
				return this._MusteriUnvani;
			}
			set
			{
				if ((this._MusteriUnvani != value))
				{
					this.OnMusteriUnvaniChanging(value);
					this.SendPropertyChanging();
					this._MusteriUnvani = value;
					this.SendPropertyChanged("MusteriUnvani");
					this.OnMusteriUnvaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(60)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(15)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bolge", DbType="NVarChar(15)")]
		public string Bolge
		{
			get
			{
				return this._Bolge;
			}
			set
			{
				if ((this._Bolge != value))
				{
					this.OnBolgeChanging(value);
					this.SendPropertyChanging();
					this._Bolge = value;
					this.SendPropertyChanged("Bolge");
					this.OnBolgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostaKodu", DbType="NVarChar(10)")]
		public string PostaKodu
		{
			get
			{
				return this._PostaKodu;
			}
			set
			{
				if ((this._PostaKodu != value))
				{
					this.OnPostaKoduChanging(value);
					this.SendPropertyChanging();
					this._PostaKodu = value;
					this.SendPropertyChanged("PostaKodu");
					this.OnPostaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NVarChar(15)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(24)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faks", DbType="NVarChar(24)")]
		public string Faks
		{
			get
			{
				return this._Faks;
			}
			set
			{
				if ((this._Faks != value))
				{
					this.OnFaksChanging(value);
					this.SendPropertyChanging();
					this._Faks = value;
					this.SendPropertyChanged("Faks");
					this.OnFaksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_MusteriMusteriDemo", Storage="_MusteriMusteriDemos", ThisKey="MusteriID", OtherKey="MusteriID")]
		public EntitySet<MusteriMusteriDemo> MusteriMusteriDemos
		{
			get
			{
				return this._MusteriMusteriDemos;
			}
			set
			{
				this._MusteriMusteriDemos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_Satislar", Storage="_Satislars", ThisKey="MusteriID", OtherKey="MusteriID")]
		public EntitySet<Satislar> Satislars
		{
			get
			{
				return this._Satislars;
			}
			set
			{
				this._Satislars.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MusteriMusteriDemos(MusteriMusteriDemo entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = this;
		}
		
		private void detach_MusteriMusteriDemos(MusteriMusteriDemo entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = null;
		}
		
		private void attach_Satislars(Satislar entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = this;
		}
		
		private void detach_Satislars(Satislar entity)
		{
			this.SendPropertyChanging();
			entity.Musteriler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MusteriMusteriDemo")]
	public partial class MusteriMusteriDemo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MusteriID;
		
		private string _MusteriTypeID;
		
		private EntityRef<MusteriDemographic> _MusteriDemographic;
		
		private EntityRef<Musteriler> _Musteriler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriIDChanging(string value);
    partial void OnMusteriIDChanged();
    partial void OnMusteriTypeIDChanging(string value);
    partial void OnMusteriTypeIDChanged();
    #endregion
		
		public MusteriMusteriDemo()
		{
			this._MusteriDemographic = default(EntityRef<MusteriDemographic>);
			this._Musteriler = default(EntityRef<Musteriler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					if (this._Musteriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriTypeID", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MusteriTypeID
		{
			get
			{
				return this._MusteriTypeID;
			}
			set
			{
				if ((this._MusteriTypeID != value))
				{
					if (this._MusteriDemographic.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriTypeIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriTypeID = value;
					this.SendPropertyChanged("MusteriTypeID");
					this.OnMusteriTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MusteriDemographic_MusteriMusteriDemo", Storage="_MusteriDemographic", ThisKey="MusteriTypeID", OtherKey="MusteriTypeID", IsForeignKey=true)]
		public MusteriDemographic MusteriDemographic
		{
			get
			{
				return this._MusteriDemographic.Entity;
			}
			set
			{
				MusteriDemographic previousValue = this._MusteriDemographic.Entity;
				if (((previousValue != value) 
							|| (this._MusteriDemographic.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MusteriDemographic.Entity = null;
						previousValue.MusteriMusteriDemos.Remove(this);
					}
					this._MusteriDemographic.Entity = value;
					if ((value != null))
					{
						value.MusteriMusteriDemos.Add(this);
						this._MusteriTypeID = value.MusteriTypeID;
					}
					else
					{
						this._MusteriTypeID = default(string);
					}
					this.SendPropertyChanged("MusteriDemographic");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_MusteriMusteriDemo", Storage="_Musteriler", ThisKey="MusteriID", OtherKey="MusteriID", IsForeignKey=true)]
		public Musteriler Musteriler
		{
			get
			{
				return this._Musteriler.Entity;
			}
			set
			{
				Musteriler previousValue = this._Musteriler.Entity;
				if (((previousValue != value) 
							|| (this._Musteriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Musteriler.Entity = null;
						previousValue.MusteriMusteriDemos.Remove(this);
					}
					this._Musteriler.Entity = value;
					if ((value != null))
					{
						value.MusteriMusteriDemos.Add(this);
						this._MusteriID = value.MusteriID;
					}
					else
					{
						this._MusteriID = default(string);
					}
					this.SendPropertyChanged("Musteriler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nakliyeciler")]
	public partial class Nakliyeciler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NakliyeciID;
		
		private string _SirketAdi;
		
		private string _Telefon;
		
		private EntitySet<Satislar> _Satislars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNakliyeciIDChanging(int value);
    partial void OnNakliyeciIDChanged();
    partial void OnSirketAdiChanging(string value);
    partial void OnSirketAdiChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public Nakliyeciler()
		{
			this._Satislars = new EntitySet<Satislar>(new Action<Satislar>(this.attach_Satislars), new Action<Satislar>(this.detach_Satislars));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NakliyeciID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NakliyeciID
		{
			get
			{
				return this._NakliyeciID;
			}
			set
			{
				if ((this._NakliyeciID != value))
				{
					this.OnNakliyeciIDChanging(value);
					this.SendPropertyChanging();
					this._NakliyeciID = value;
					this.SendPropertyChanged("NakliyeciID");
					this.OnNakliyeciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SirketAdi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string SirketAdi
		{
			get
			{
				return this._SirketAdi;
			}
			set
			{
				if ((this._SirketAdi != value))
				{
					this.OnSirketAdiChanging(value);
					this.SendPropertyChanging();
					this._SirketAdi = value;
					this.SendPropertyChanged("SirketAdi");
					this.OnSirketAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(24)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nakliyeciler_Satislar", Storage="_Satislars", ThisKey="NakliyeciID", OtherKey="ShipVia")]
		public EntitySet<Satislar> Satislars
		{
			get
			{
				return this._Satislars;
			}
			set
			{
				this._Satislars.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Satislars(Satislar entity)
		{
			this.SendPropertyChanging();
			entity.Nakliyeciler = this;
		}
		
		private void detach_Satislars(Satislar entity)
		{
			this.SendPropertyChanging();
			entity.Nakliyeciler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonelBolgeler")]
	public partial class PersonelBolgeler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonelID;
		
		private string _TerritoryID;
		
		private EntityRef<Bolgeler> _Bolgeler;
		
		private EntityRef<Personeller> _Personeller;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonelIDChanging(int value);
    partial void OnPersonelIDChanged();
    partial void OnTerritoryIDChanging(string value);
    partial void OnTerritoryIDChanged();
    #endregion
		
		public PersonelBolgeler()
		{
			this._Bolgeler = default(EntityRef<Bolgeler>);
			this._Personeller = default(EntityRef<Personeller>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					if (this._Personeller.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TerritoryID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TerritoryID
		{
			get
			{
				return this._TerritoryID;
			}
			set
			{
				if ((this._TerritoryID != value))
				{
					if (this._Bolgeler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTerritoryIDChanging(value);
					this.SendPropertyChanging();
					this._TerritoryID = value;
					this.SendPropertyChanged("TerritoryID");
					this.OnTerritoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolgeler_PersonelBolgeler", Storage="_Bolgeler", ThisKey="TerritoryID", OtherKey="TerritoryID", IsForeignKey=true)]
		public Bolgeler Bolgeler
		{
			get
			{
				return this._Bolgeler.Entity;
			}
			set
			{
				Bolgeler previousValue = this._Bolgeler.Entity;
				if (((previousValue != value) 
							|| (this._Bolgeler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bolgeler.Entity = null;
						previousValue.PersonelBolgelers.Remove(this);
					}
					this._Bolgeler.Entity = value;
					if ((value != null))
					{
						value.PersonelBolgelers.Add(this);
						this._TerritoryID = value.TerritoryID;
					}
					else
					{
						this._TerritoryID = default(string);
					}
					this.SendPropertyChanged("Bolgeler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeller_PersonelBolgeler", Storage="_Personeller", ThisKey="PersonelID", OtherKey="PersonelID", IsForeignKey=true)]
		public Personeller Personeller
		{
			get
			{
				return this._Personeller.Entity;
			}
			set
			{
				Personeller previousValue = this._Personeller.Entity;
				if (((previousValue != value) 
							|| (this._Personeller.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personeller.Entity = null;
						previousValue.PersonelBolgelers.Remove(this);
					}
					this._Personeller.Entity = value;
					if ((value != null))
					{
						value.PersonelBolgelers.Add(this);
						this._PersonelID = value.PersonelID;
					}
					else
					{
						this._PersonelID = default(int);
					}
					this.SendPropertyChanged("Personeller");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personeller")]
	public partial class Personeller : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonelID;
		
		private string _SoyAdi;
		
		private string _Adi;
		
		private string _Unvan;
		
		private string _UnvanEki;
		
		private System.Nullable<System.DateTime> _DogumTarihi;
		
		private System.Nullable<System.DateTime> _IseBaslamaTarihi;
		
		private string _Adres;
		
		private string _Sehir;
		
		private string _Bolge;
		
		private string _PostaKodu;
		
		private string _Ulke;
		
		private string _EvTelefonu;
		
		private string _Extension;
		
		private System.Data.Linq.Binary _Fotograf;
		
		private string _Notlar;
		
		private System.Nullable<int> _BagliCalistigiKisi;
		
		private string _FotografPath;
		
		private EntitySet<PersonelBolgeler> _PersonelBolgelers;
		
		private EntitySet<Personeller> _Personellers;
		
		private EntitySet<Satislar> _Satislars;
		
		private EntityRef<Personeller> _Personeller1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonelIDChanging(int value);
    partial void OnPersonelIDChanged();
    partial void OnSoyAdiChanging(string value);
    partial void OnSoyAdiChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnUnvanChanging(string value);
    partial void OnUnvanChanged();
    partial void OnUnvanEkiChanging(string value);
    partial void OnUnvanEkiChanged();
    partial void OnDogumTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnDogumTarihiChanged();
    partial void OnIseBaslamaTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnIseBaslamaTarihiChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnBolgeChanging(string value);
    partial void OnBolgeChanged();
    partial void OnPostaKoduChanging(string value);
    partial void OnPostaKoduChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OnEvTelefonuChanging(string value);
    partial void OnEvTelefonuChanged();
    partial void OnExtensionChanging(string value);
    partial void OnExtensionChanged();
    partial void OnFotografChanging(System.Data.Linq.Binary value);
    partial void OnFotografChanged();
    partial void OnNotlarChanging(string value);
    partial void OnNotlarChanged();
    partial void OnBagliCalistigiKisiChanging(System.Nullable<int> value);
    partial void OnBagliCalistigiKisiChanged();
    partial void OnFotografPathChanging(string value);
    partial void OnFotografPathChanged();
    #endregion
		
		public Personeller()
		{
			this._PersonelBolgelers = new EntitySet<PersonelBolgeler>(new Action<PersonelBolgeler>(this.attach_PersonelBolgelers), new Action<PersonelBolgeler>(this.detach_PersonelBolgelers));
			this._Personellers = new EntitySet<Personeller>(new Action<Personeller>(this.attach_Personellers), new Action<Personeller>(this.detach_Personellers));
			this._Satislars = new EntitySet<Satislar>(new Action<Satislar>(this.attach_Satislars), new Action<Satislar>(this.detach_Satislars));
			this._Personeller1 = default(EntityRef<Personeller>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoyAdi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SoyAdi
		{
			get
			{
				return this._SoyAdi;
			}
			set
			{
				if ((this._SoyAdi != value))
				{
					this.OnSoyAdiChanging(value);
					this.SendPropertyChanging();
					this._SoyAdi = value;
					this.SendPropertyChanged("SoyAdi");
					this.OnSoyAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unvan", DbType="NVarChar(30)")]
		public string Unvan
		{
			get
			{
				return this._Unvan;
			}
			set
			{
				if ((this._Unvan != value))
				{
					this.OnUnvanChanging(value);
					this.SendPropertyChanging();
					this._Unvan = value;
					this.SendPropertyChanged("Unvan");
					this.OnUnvanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnvanEki", DbType="NVarChar(25)")]
		public string UnvanEki
		{
			get
			{
				return this._UnvanEki;
			}
			set
			{
				if ((this._UnvanEki != value))
				{
					this.OnUnvanEkiChanging(value);
					this.SendPropertyChanging();
					this._UnvanEki = value;
					this.SendPropertyChanged("UnvanEki");
					this.OnUnvanEkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> DogumTarihi
		{
			get
			{
				return this._DogumTarihi;
			}
			set
			{
				if ((this._DogumTarihi != value))
				{
					this.OnDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._DogumTarihi = value;
					this.SendPropertyChanged("DogumTarihi");
					this.OnDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseBaslamaTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IseBaslamaTarihi
		{
			get
			{
				return this._IseBaslamaTarihi;
			}
			set
			{
				if ((this._IseBaslamaTarihi != value))
				{
					this.OnIseBaslamaTarihiChanging(value);
					this.SendPropertyChanging();
					this._IseBaslamaTarihi = value;
					this.SendPropertyChanged("IseBaslamaTarihi");
					this.OnIseBaslamaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(60)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(15)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bolge", DbType="NVarChar(15)")]
		public string Bolge
		{
			get
			{
				return this._Bolge;
			}
			set
			{
				if ((this._Bolge != value))
				{
					this.OnBolgeChanging(value);
					this.SendPropertyChanging();
					this._Bolge = value;
					this.SendPropertyChanged("Bolge");
					this.OnBolgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostaKodu", DbType="NVarChar(10)")]
		public string PostaKodu
		{
			get
			{
				return this._PostaKodu;
			}
			set
			{
				if ((this._PostaKodu != value))
				{
					this.OnPostaKoduChanging(value);
					this.SendPropertyChanging();
					this._PostaKodu = value;
					this.SendPropertyChanged("PostaKodu");
					this.OnPostaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NVarChar(15)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvTelefonu", DbType="NVarChar(24)")]
		public string EvTelefonu
		{
			get
			{
				return this._EvTelefonu;
			}
			set
			{
				if ((this._EvTelefonu != value))
				{
					this.OnEvTelefonuChanging(value);
					this.SendPropertyChanging();
					this._EvTelefonu = value;
					this.SendPropertyChanged("EvTelefonu");
					this.OnEvTelefonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="NVarChar(4)")]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this.OnExtensionChanging(value);
					this.SendPropertyChanging();
					this._Extension = value;
					this.SendPropertyChanged("Extension");
					this.OnExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fotograf", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Fotograf
		{
			get
			{
				return this._Fotograf;
			}
			set
			{
				if ((this._Fotograf != value))
				{
					this.OnFotografChanging(value);
					this.SendPropertyChanging();
					this._Fotograf = value;
					this.SendPropertyChanged("Fotograf");
					this.OnFotografChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notlar", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Notlar
		{
			get
			{
				return this._Notlar;
			}
			set
			{
				if ((this._Notlar != value))
				{
					this.OnNotlarChanging(value);
					this.SendPropertyChanging();
					this._Notlar = value;
					this.SendPropertyChanged("Notlar");
					this.OnNotlarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BagliCalistigiKisi", DbType="Int")]
		public System.Nullable<int> BagliCalistigiKisi
		{
			get
			{
				return this._BagliCalistigiKisi;
			}
			set
			{
				if ((this._BagliCalistigiKisi != value))
				{
					if (this._Personeller1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBagliCalistigiKisiChanging(value);
					this.SendPropertyChanging();
					this._BagliCalistigiKisi = value;
					this.SendPropertyChanged("BagliCalistigiKisi");
					this.OnBagliCalistigiKisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotografPath", DbType="NVarChar(255)")]
		public string FotografPath
		{
			get
			{
				return this._FotografPath;
			}
			set
			{
				if ((this._FotografPath != value))
				{
					this.OnFotografPathChanging(value);
					this.SendPropertyChanging();
					this._FotografPath = value;
					this.SendPropertyChanged("FotografPath");
					this.OnFotografPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeller_PersonelBolgeler", Storage="_PersonelBolgelers", ThisKey="PersonelID", OtherKey="PersonelID")]
		public EntitySet<PersonelBolgeler> PersonelBolgelers
		{
			get
			{
				return this._PersonelBolgelers;
			}
			set
			{
				this._PersonelBolgelers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeller_Personeller", Storage="_Personellers", ThisKey="PersonelID", OtherKey="BagliCalistigiKisi")]
		public EntitySet<Personeller> Personellers
		{
			get
			{
				return this._Personellers;
			}
			set
			{
				this._Personellers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeller_Satislar", Storage="_Satislars", ThisKey="PersonelID", OtherKey="PersonelID")]
		public EntitySet<Satislar> Satislars
		{
			get
			{
				return this._Satislars;
			}
			set
			{
				this._Satislars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeller_Personeller", Storage="_Personeller1", ThisKey="BagliCalistigiKisi", OtherKey="PersonelID", IsForeignKey=true)]
		public Personeller Personeller1
		{
			get
			{
				return this._Personeller1.Entity;
			}
			set
			{
				Personeller previousValue = this._Personeller1.Entity;
				if (((previousValue != value) 
							|| (this._Personeller1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personeller1.Entity = null;
						previousValue.Personellers.Remove(this);
					}
					this._Personeller1.Entity = value;
					if ((value != null))
					{
						value.Personellers.Add(this);
						this._BagliCalistigiKisi = value.PersonelID;
					}
					else
					{
						this._BagliCalistigiKisi = default(Nullable<int>);
					}
					this.SendPropertyChanged("Personeller1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PersonelBolgelers(PersonelBolgeler entity)
		{
			this.SendPropertyChanging();
			entity.Personeller = this;
		}
		
		private void detach_PersonelBolgelers(PersonelBolgeler entity)
		{
			this.SendPropertyChanging();
			entity.Personeller = null;
		}
		
		private void attach_Personellers(Personeller entity)
		{
			this.SendPropertyChanging();
			entity.Personeller1 = this;
		}
		
		private void detach_Personellers(Personeller entity)
		{
			this.SendPropertyChanging();
			entity.Personeller1 = null;
		}
		
		private void attach_Satislars(Satislar entity)
		{
			this.SendPropertyChanging();
			entity.Personeller = this;
		}
		
		private void detach_Satislars(Satislar entity)
		{
			this.SendPropertyChanging();
			entity.Personeller = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SatisDetay")]
	public partial class SatisDetay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatisID;
		
		private int _UrunID;
		
		private decimal _Fiyat;
		
		private short _Adet;
		
		private float _Indirim;
		
		private EntityRef<Urunler> _Urunler;
		
		private EntityRef<Satislar> _Satislar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatisIDChanging(int value);
    partial void OnSatisIDChanged();
    partial void OnUrunIDChanging(int value);
    partial void OnUrunIDChanged();
    partial void OnFiyatChanging(decimal value);
    partial void OnFiyatChanged();
    partial void OnAdetChanging(short value);
    partial void OnAdetChanged();
    partial void OnIndirimChanging(float value);
    partial void OnIndirimChanged();
    #endregion
		
		public SatisDetay()
		{
			this._Urunler = default(EntityRef<Urunler>);
			this._Satislar = default(EntityRef<Satislar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SatisID
		{
			get
			{
				return this._SatisID;
			}
			set
			{
				if ((this._SatisID != value))
				{
					if (this._Satislar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSatisIDChanging(value);
					this.SendPropertyChanging();
					this._SatisID = value;
					this.SendPropertyChanged("SatisID");
					this.OnSatisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					if (this._Urunler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fiyat", DbType="Money NOT NULL")]
		public decimal Fiyat
		{
			get
			{
				return this._Fiyat;
			}
			set
			{
				if ((this._Fiyat != value))
				{
					this.OnFiyatChanging(value);
					this.SendPropertyChanging();
					this._Fiyat = value;
					this.SendPropertyChanged("Fiyat");
					this.OnFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="SmallInt NOT NULL")]
		public short Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indirim", DbType="Real NOT NULL")]
		public float Indirim
		{
			get
			{
				return this._Indirim;
			}
			set
			{
				if ((this._Indirim != value))
				{
					this.OnIndirimChanging(value);
					this.SendPropertyChanging();
					this._Indirim = value;
					this.SendPropertyChanged("Indirim");
					this.OnIndirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urunler_SatisDetay", Storage="_Urunler", ThisKey="UrunID", OtherKey="UrunID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Urunler Urunler
		{
			get
			{
				return this._Urunler.Entity;
			}
			set
			{
				Urunler previousValue = this._Urunler.Entity;
				if (((previousValue != value) 
							|| (this._Urunler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Urunler.Entity = null;
						previousValue.SatisDetays.Remove(this);
					}
					this._Urunler.Entity = value;
					if ((value != null))
					{
						value.SatisDetays.Add(this);
						this._UrunID = value.UrunID;
					}
					else
					{
						this._UrunID = default(int);
					}
					this.SendPropertyChanged("Urunler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Satislar_SatisDetay", Storage="_Satislar", ThisKey="SatisID", OtherKey="SatisID", IsForeignKey=true)]
		public Satislar Satislar
		{
			get
			{
				return this._Satislar.Entity;
			}
			set
			{
				Satislar previousValue = this._Satislar.Entity;
				if (((previousValue != value) 
							|| (this._Satislar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Satislar.Entity = null;
						previousValue.SatisDetays.Remove(this);
					}
					this._Satislar.Entity = value;
					if ((value != null))
					{
						value.SatisDetays.Add(this);
						this._SatisID = value.SatisID;
					}
					else
					{
						this._SatisID = default(int);
					}
					this.SendPropertyChanged("Satislar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Satislar")]
	public partial class Satislar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatisID;
		
		private string _MusteriID;
		
		private System.Nullable<int> _PersonelID;
		
		private System.Nullable<System.DateTime> _SatisTarihi;
		
		private System.Nullable<System.DateTime> _OdemeTarihi;
		
		private System.Nullable<System.DateTime> _SevkTarihi;
		
		private System.Nullable<int> _ShipVia;
		
		private System.Nullable<decimal> _NakliyeUcreti;
		
		private string _SevkAdi;
		
		private string _SevkAdresi;
		
		private string _SevkSehri;
		
		private string _SevkBolgesi;
		
		private string _SevkPostaKodu;
		
		private string _SevkUlkesi;
		
		private EntitySet<SatisDetay> _SatisDetays;
		
		private EntityRef<Musteriler> _Musteriler;
		
		private EntityRef<Nakliyeciler> _Nakliyeciler;
		
		private EntityRef<Personeller> _Personeller;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatisIDChanging(int value);
    partial void OnSatisIDChanged();
    partial void OnMusteriIDChanging(string value);
    partial void OnMusteriIDChanged();
    partial void OnPersonelIDChanging(System.Nullable<int> value);
    partial void OnPersonelIDChanged();
    partial void OnSatisTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSatisTarihiChanged();
    partial void OnOdemeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOdemeTarihiChanged();
    partial void OnSevkTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnSevkTarihiChanged();
    partial void OnShipViaChanging(System.Nullable<int> value);
    partial void OnShipViaChanged();
    partial void OnNakliyeUcretiChanging(System.Nullable<decimal> value);
    partial void OnNakliyeUcretiChanged();
    partial void OnSevkAdiChanging(string value);
    partial void OnSevkAdiChanged();
    partial void OnSevkAdresiChanging(string value);
    partial void OnSevkAdresiChanged();
    partial void OnSevkSehriChanging(string value);
    partial void OnSevkSehriChanged();
    partial void OnSevkBolgesiChanging(string value);
    partial void OnSevkBolgesiChanged();
    partial void OnSevkPostaKoduChanging(string value);
    partial void OnSevkPostaKoduChanged();
    partial void OnSevkUlkesiChanging(string value);
    partial void OnSevkUlkesiChanged();
    #endregion
		
		public Satislar()
		{
			this._SatisDetays = new EntitySet<SatisDetay>(new Action<SatisDetay>(this.attach_SatisDetays), new Action<SatisDetay>(this.detach_SatisDetays));
			this._Musteriler = default(EntityRef<Musteriler>);
			this._Nakliyeciler = default(EntityRef<Nakliyeciler>);
			this._Personeller = default(EntityRef<Personeller>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SatisID
		{
			get
			{
				return this._SatisID;
			}
			set
			{
				if ((this._SatisID != value))
				{
					this.OnSatisIDChanging(value);
					this.SendPropertyChanging();
					this._SatisID = value;
					this.SendPropertyChanged("SatisID");
					this.OnSatisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", DbType="NChar(5)")]
		public string MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					if (this._Musteriler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int")]
		public System.Nullable<int> PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					if (this._Personeller.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SatisTarihi
		{
			get
			{
				return this._SatisTarihi;
			}
			set
			{
				if ((this._SatisTarihi != value))
				{
					this.OnSatisTarihiChanging(value);
					this.SendPropertyChanging();
					this._SatisTarihi = value;
					this.SendPropertyChanged("SatisTarihi");
					this.OnSatisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> OdemeTarihi
		{
			get
			{
				return this._OdemeTarihi;
			}
			set
			{
				if ((this._OdemeTarihi != value))
				{
					this.OnOdemeTarihiChanging(value);
					this.SendPropertyChanging();
					this._OdemeTarihi = value;
					this.SendPropertyChanged("OdemeTarihi");
					this.OnOdemeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SevkTarihi
		{
			get
			{
				return this._SevkTarihi;
			}
			set
			{
				if ((this._SevkTarihi != value))
				{
					this.OnSevkTarihiChanging(value);
					this.SendPropertyChanging();
					this._SevkTarihi = value;
					this.SendPropertyChanged("SevkTarihi");
					this.OnSevkTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipVia", DbType="Int")]
		public System.Nullable<int> ShipVia
		{
			get
			{
				return this._ShipVia;
			}
			set
			{
				if ((this._ShipVia != value))
				{
					if (this._Nakliyeciler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShipViaChanging(value);
					this.SendPropertyChanging();
					this._ShipVia = value;
					this.SendPropertyChanged("ShipVia");
					this.OnShipViaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NakliyeUcreti", DbType="Money")]
		public System.Nullable<decimal> NakliyeUcreti
		{
			get
			{
				return this._NakliyeUcreti;
			}
			set
			{
				if ((this._NakliyeUcreti != value))
				{
					this.OnNakliyeUcretiChanging(value);
					this.SendPropertyChanging();
					this._NakliyeUcreti = value;
					this.SendPropertyChanged("NakliyeUcreti");
					this.OnNakliyeUcretiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkAdi", DbType="NVarChar(40)")]
		public string SevkAdi
		{
			get
			{
				return this._SevkAdi;
			}
			set
			{
				if ((this._SevkAdi != value))
				{
					this.OnSevkAdiChanging(value);
					this.SendPropertyChanging();
					this._SevkAdi = value;
					this.SendPropertyChanged("SevkAdi");
					this.OnSevkAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkAdresi", DbType="NVarChar(60)")]
		public string SevkAdresi
		{
			get
			{
				return this._SevkAdresi;
			}
			set
			{
				if ((this._SevkAdresi != value))
				{
					this.OnSevkAdresiChanging(value);
					this.SendPropertyChanging();
					this._SevkAdresi = value;
					this.SendPropertyChanged("SevkAdresi");
					this.OnSevkAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkSehri", DbType="NVarChar(15)")]
		public string SevkSehri
		{
			get
			{
				return this._SevkSehri;
			}
			set
			{
				if ((this._SevkSehri != value))
				{
					this.OnSevkSehriChanging(value);
					this.SendPropertyChanging();
					this._SevkSehri = value;
					this.SendPropertyChanged("SevkSehri");
					this.OnSevkSehriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkBolgesi", DbType="NVarChar(15)")]
		public string SevkBolgesi
		{
			get
			{
				return this._SevkBolgesi;
			}
			set
			{
				if ((this._SevkBolgesi != value))
				{
					this.OnSevkBolgesiChanging(value);
					this.SendPropertyChanging();
					this._SevkBolgesi = value;
					this.SendPropertyChanged("SevkBolgesi");
					this.OnSevkBolgesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkPostaKodu", DbType="NVarChar(10)")]
		public string SevkPostaKodu
		{
			get
			{
				return this._SevkPostaKodu;
			}
			set
			{
				if ((this._SevkPostaKodu != value))
				{
					this.OnSevkPostaKoduChanging(value);
					this.SendPropertyChanging();
					this._SevkPostaKodu = value;
					this.SendPropertyChanged("SevkPostaKodu");
					this.OnSevkPostaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SevkUlkesi", DbType="NVarChar(15)")]
		public string SevkUlkesi
		{
			get
			{
				return this._SevkUlkesi;
			}
			set
			{
				if ((this._SevkUlkesi != value))
				{
					this.OnSevkUlkesiChanging(value);
					this.SendPropertyChanging();
					this._SevkUlkesi = value;
					this.SendPropertyChanged("SevkUlkesi");
					this.OnSevkUlkesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Satislar_SatisDetay", Storage="_SatisDetays", ThisKey="SatisID", OtherKey="SatisID")]
		public EntitySet<SatisDetay> SatisDetays
		{
			get
			{
				return this._SatisDetays;
			}
			set
			{
				this._SatisDetays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteriler_Satislar", Storage="_Musteriler", ThisKey="MusteriID", OtherKey="MusteriID", IsForeignKey=true)]
		public Musteriler Musteriler
		{
			get
			{
				return this._Musteriler.Entity;
			}
			set
			{
				Musteriler previousValue = this._Musteriler.Entity;
				if (((previousValue != value) 
							|| (this._Musteriler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Musteriler.Entity = null;
						previousValue.Satislars.Remove(this);
					}
					this._Musteriler.Entity = value;
					if ((value != null))
					{
						value.Satislars.Add(this);
						this._MusteriID = value.MusteriID;
					}
					else
					{
						this._MusteriID = default(string);
					}
					this.SendPropertyChanged("Musteriler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nakliyeciler_Satislar", Storage="_Nakliyeciler", ThisKey="ShipVia", OtherKey="NakliyeciID", IsForeignKey=true)]
		public Nakliyeciler Nakliyeciler
		{
			get
			{
				return this._Nakliyeciler.Entity;
			}
			set
			{
				Nakliyeciler previousValue = this._Nakliyeciler.Entity;
				if (((previousValue != value) 
							|| (this._Nakliyeciler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nakliyeciler.Entity = null;
						previousValue.Satislars.Remove(this);
					}
					this._Nakliyeciler.Entity = value;
					if ((value != null))
					{
						value.Satislars.Add(this);
						this._ShipVia = value.NakliyeciID;
					}
					else
					{
						this._ShipVia = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nakliyeciler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personeller_Satislar", Storage="_Personeller", ThisKey="PersonelID", OtherKey="PersonelID", IsForeignKey=true)]
		public Personeller Personeller
		{
			get
			{
				return this._Personeller.Entity;
			}
			set
			{
				Personeller previousValue = this._Personeller.Entity;
				if (((previousValue != value) 
							|| (this._Personeller.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personeller.Entity = null;
						previousValue.Satislars.Remove(this);
					}
					this._Personeller.Entity = value;
					if ((value != null))
					{
						value.Satislars.Add(this);
						this._PersonelID = value.PersonelID;
					}
					else
					{
						this._PersonelID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Personeller");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SatisDetays(SatisDetay entity)
		{
			this.SendPropertyChanging();
			entity.Satislar = this;
		}
		
		private void detach_SatisDetays(SatisDetay entity)
		{
			this.SendPropertyChanging();
			entity.Satislar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tedarikciler")]
	public partial class Tedarikciler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TedarikciID;
		
		private string _SirketAdi;
		
		private string _MusteriAdi;
		
		private string _MusteriUnvani;
		
		private string _Adres;
		
		private string _Sehir;
		
		private string _Bolge;
		
		private string _PostaKodu;
		
		private string _Ulke;
		
		private string _Telefon;
		
		private string _Faks;
		
		private string _WebSayfasi;
		
		private EntitySet<Urunler> _Urunlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTedarikciIDChanging(int value);
    partial void OnTedarikciIDChanged();
    partial void OnSirketAdiChanging(string value);
    partial void OnSirketAdiChanged();
    partial void OnMusteriAdiChanging(string value);
    partial void OnMusteriAdiChanged();
    partial void OnMusteriUnvaniChanging(string value);
    partial void OnMusteriUnvaniChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnBolgeChanging(string value);
    partial void OnBolgeChanged();
    partial void OnPostaKoduChanging(string value);
    partial void OnPostaKoduChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnFaksChanging(string value);
    partial void OnFaksChanged();
    partial void OnWebSayfasiChanging(string value);
    partial void OnWebSayfasiChanged();
    #endregion
		
		public Tedarikciler()
		{
			this._Urunlers = new EntitySet<Urunler>(new Action<Urunler>(this.attach_Urunlers), new Action<Urunler>(this.detach_Urunlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TedarikciID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TedarikciID
		{
			get
			{
				return this._TedarikciID;
			}
			set
			{
				if ((this._TedarikciID != value))
				{
					this.OnTedarikciIDChanging(value);
					this.SendPropertyChanging();
					this._TedarikciID = value;
					this.SendPropertyChanged("TedarikciID");
					this.OnTedarikciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SirketAdi", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string SirketAdi
		{
			get
			{
				return this._SirketAdi;
			}
			set
			{
				if ((this._SirketAdi != value))
				{
					this.OnSirketAdiChanging(value);
					this.SendPropertyChanging();
					this._SirketAdi = value;
					this.SendPropertyChanged("SirketAdi");
					this.OnSirketAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAdi", DbType="NVarChar(30)")]
		public string MusteriAdi
		{
			get
			{
				return this._MusteriAdi;
			}
			set
			{
				if ((this._MusteriAdi != value))
				{
					this.OnMusteriAdiChanging(value);
					this.SendPropertyChanging();
					this._MusteriAdi = value;
					this.SendPropertyChanged("MusteriAdi");
					this.OnMusteriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriUnvani", DbType="NVarChar(30)")]
		public string MusteriUnvani
		{
			get
			{
				return this._MusteriUnvani;
			}
			set
			{
				if ((this._MusteriUnvani != value))
				{
					this.OnMusteriUnvaniChanging(value);
					this.SendPropertyChanging();
					this._MusteriUnvani = value;
					this.SendPropertyChanged("MusteriUnvani");
					this.OnMusteriUnvaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(60)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(15)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bolge", DbType="NVarChar(15)")]
		public string Bolge
		{
			get
			{
				return this._Bolge;
			}
			set
			{
				if ((this._Bolge != value))
				{
					this.OnBolgeChanging(value);
					this.SendPropertyChanging();
					this._Bolge = value;
					this.SendPropertyChanged("Bolge");
					this.OnBolgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostaKodu", DbType="NVarChar(10)")]
		public string PostaKodu
		{
			get
			{
				return this._PostaKodu;
			}
			set
			{
				if ((this._PostaKodu != value))
				{
					this.OnPostaKoduChanging(value);
					this.SendPropertyChanging();
					this._PostaKodu = value;
					this.SendPropertyChanged("PostaKodu");
					this.OnPostaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NVarChar(15)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(24)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faks", DbType="NVarChar(24)")]
		public string Faks
		{
			get
			{
				return this._Faks;
			}
			set
			{
				if ((this._Faks != value))
				{
					this.OnFaksChanging(value);
					this.SendPropertyChanging();
					this._Faks = value;
					this.SendPropertyChanged("Faks");
					this.OnFaksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebSayfasi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string WebSayfasi
		{
			get
			{
				return this._WebSayfasi;
			}
			set
			{
				if ((this._WebSayfasi != value))
				{
					this.OnWebSayfasiChanging(value);
					this.SendPropertyChanging();
					this._WebSayfasi = value;
					this.SendPropertyChanged("WebSayfasi");
					this.OnWebSayfasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tedarikciler_Urunler", Storage="_Urunlers", ThisKey="TedarikciID", OtherKey="TedarikciID")]
		public EntitySet<Urunler> Urunlers
		{
			get
			{
				return this._Urunlers;
			}
			set
			{
				this._Urunlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Tedarikciler = this;
		}
		
		private void detach_Urunlers(Urunler entity)
		{
			this.SendPropertyChanging();
			entity.Tedarikciler = null;
		}
	}
}
#pragma warning restore 1591
